return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "VeryLazy", "BufReadPost", "BufNewFile", "BufWritePre" },
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "awk",
        "bash",
        "diff",
        "dockerfile",
        "hcl",
        "html",
        "json",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "scala",
        "sql",
        "terraform",
        "toml",
        "yaml",
      },
      highlight = { enable = true },
      indent = { enable = true, disable = { "python" } },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<c-space>",
          node_incremental = "<c-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },
}
