#!/usr/bin/env sh

# Unlock Bitwarden when necessary
if test -z "$BW_SESSION"
then
	echo "No Bitwarden session was found!"
	exit 1
fi

(echo "$(bw get password onelogin)"; echo "$(bw get totp onelogin)") | \
	sudo openconnect --user=mathias.lavaert@persgroep.net \
			 --juniper https://homeworker.persgroep.net \
			 --no-dtls
